steps:
  # Step 1: Dataform Compile - ensures SQLX files have no syntax errors
  - name: 'dataformco/dataform:latest'
    entrypoint: ''
    args:
      - bash
      - '-c'
      - |
        dataform install
        dataform compile

  # Step 2: Dataform Dry Run - simulates the execution of SQLX queries
  - name: 'dataformco/dataform:latest'
    entrypoint: ''
    args:
      - bash
      - '-c'
      - |
        dataform install
        dataform run --dry-run

  # Step 3: Dataform Run - deploys the changes to BigQuery (e.g., tables and views)
  - name: 'dataformco/dataform:latest'
    entrypoint: ''
    args:
      - bash
      - '-c'
      - |
        dataform install
        dataform run

timeout: '1200s'  # Timeout after 20 minutes

options:
  logging: CLOUD_LOGGING_ONLY 

