steps:
  # Create a clean temporary directory
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/temp_dir && cd /workspace/temp_dir

  # Install Node.js and Dataform in the temporary directory
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install @dataform/cli && echo "Dataform installed successfully." || echo "Dataform installation failed."
        cd /workspace/temp_dir

  # Run the Dataform models
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/temp_dir && npx dataform run  # This runs the Dataform models

timeout: '1200s'  # Adjust timeout as needed

substitutions:
  _DATAFORM_PROJECT: 'demo-workspace'
options:
  logging: CLOUD_LOGGING_ONLY
